export enum FilterObjects {
    RICH_TEXT = 'rich_text',
    PHONE_NUMBER = 'phone_number',
    NUMBER = 'number',
    SELECT = 'select',
    MULTI_SELECT = 'multi_select',
    DATE = 'date',
    PEOPLE = 'people',
    FILES = 'files',
    CHECKBOX = 'checkbox',
    URL = 'url',
    EMAIL = 'email',
    FORMULA = 'formula',
    RELATION = 'relation',
    ROLLUP = 'rollup',
    CREATED_TIME = 'created_time',
    CREATED_BY = 'created_by',
}