name: PageData Revalidator 
on:
  push:
   branches: 
    - main
  schedule:
    - cron: '*/50 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly cron job
        run: |
          curl --request POST \
          --url 'https://wtfmvmt.com/api/revalidate' \
          --header 'Authorization: Bearer ${{ secrets.REVALIDATION_TOKEN }}'\
          \
          curl --request GET \
          --url 'https://wtfmvmt.com/' \